### ISSUE TITLE
Crash on development branch

### ISSUE THREAD

**Issue by lylavoie** [weewx/weewx#359] opened 2018-11-28 23:11 UTC
Been running the development branch for a few days, so I can use the new Essential Values feature for pushing data to weather underground.  System had a crash.  Here are all the debug logs, in case this helps (not filling a specific bug).

Nov 27 01:43:18 raspberrypi weewx[7964]: restx: StationRegistry: wait interval (24300 < 604800) has not passed for record 2018-11-27 01:43:00 EST (1543300980)
Nov 27 01:43:18 raspberrypi weewx[7964]: wmr200: MainThread: D genLoop() phase getting live packets
Nov 27 01:43:18 raspberrypi weewx[7964]: wmr200: MainThread: D   Queuing live packet rx:16191 live_queue_len:1
Nov 27 01:43:18 raspberrypi weewx[7964]: reportengine: Running reports for latest time in the database.
Nov 27 01:43:18 raspberrypi weewx[7964]: reportengine: Running report 'SeasonsReport'
Nov 27 01:43:18 raspberrypi weewx[7964]: restx: PWSWeather: Published record 2018-11-27 01:43:00 EST (1543300980)
Nov 27 01:43:18 raspberrypi weewx[7964]: reportengine: Found configuration file /usr/local/weewx/skins/Seasons/skin.conf for report 'SeasonsReport'
Nov 27 01:43:18 raspberrypi weewx[7964]: restx: Wunderground-PWS: Published record 2018-11-27 01:43:00 EST (1543300980)
Nov 27 01:43:18 raspberrypi weewx[7964]: cheetahgenerator: using search list ['weewx.cheetahgenerator.Almanac', 'weewx.cheetahgenerator.Station', 'weewx.cheetahgenerator.Current', 'weewx.cheetahgenerator.Stats', 'weewx.cheetahgenerator.UnitInfo', 'weewx.
Nov 27 01:43:18 raspberrypi weewx[7964]: manager: Daily summary version is 2.0
Nov 27 01:43:19 raspberrypi weewx[7964]: wmr200: MainThread: D genLoop() Yielding live queued packet id:21962
Nov 27 01:43:20 raspberrypi weewx[7964]: wmr200: MainThread: D   Queuing live packet rx:16192 live_queue_len:1
Nov 27 01:43:21 raspberrypi weewx[7964]: wmr200: MainThread: D genLoop() Yielding live queued packet id:21963
Nov 27 01:43:29 raspberrypi weewx[7964]: cheetahgenerator: Generated 8 files for report SeasonsReport in 11.08 seconds
Nov 27 01:43:29 raspberrypi weewx[7964]: manager: Daily summary version is 2.0
Nov 27 01:43:30 raspberrypi weewx[7964]: wmr200: MainThread: D   Acknowledged control packet rx:5768
Nov 27 01:43:36 raspberrypi weewx[7964]: imagegenerator: Generated 14 images for SeasonsReport in 6.89 seconds
Nov 27 01:43:36 raspberrypi weewx[7964]: copygenerator: copied 0 files to /var/www/html/weewx
Nov 27 01:43:36 raspberrypi weewx[7964]: reportengine: Report 'SmartphoneReport' not enabled. Skipping.
Nov 27 01:43:36 raspberrypi weewx[7964]: reportengine: Report 'MobileReport' not enabled. Skipping.
Nov 27 01:43:36 raspberrypi weewx[7964]: reportengine: Report 'StandardReport' not enabled. Skipping.
Nov 27 01:43:36 raspberrypi weewx[7964]: reportengine: Report 'FTP' not enabled. Skipping.
Nov 27 01:43:36 raspberrypi weewx[7964]: reportengine: Report 'RSYNC' not enabled. Skipping.
Nov 27 01:43:44 raspberrypi weewx[7964]: wmr200: Thread-8: E read_device() USB Error Reason:[Errno 110] Operation timed out
Nov 27 01:43:44 raspberrypi weewx[7964]: wmr200: Thread-8: E USB device read error
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: MainThread: E USB polling thread unexpectedly terminated
Nov 27 01:43:45 raspberrypi weewx[7964]: engine: Main loop exiting. Shutting engine down.
Nov 27 01:43:45 raspberrypi weewx[7964]: engine: Shutting down StdReport thread
Nov 27 01:43:45 raspberrypi weewx[7964]: engine: StdReport thread has been terminated
Nov 27 01:43:45 raspberrypi weewx[7964]: restx: Shut down PWSWeather thread.
Nov 27 01:43:45 raspberrypi weewx[7964]: restx: Shut down Wunderground-PWS thread.
Nov 27 01:43:45 raspberrypi weewx[7964]: restx: Shut down StationRegistry thread.
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: MainThread: I USB polling thread expired
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: Thread-7: I Watchdog received shutdown
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: Thread-7: I Watchdog thread exiting
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: MainThread: I Watchdog thread expired
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: MainThread: I Received packet count live:16192 archive:4 control:5768
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: MainThread: I Received bytes:287224 sent bytes:18376
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: MainThread: I Packet archive queue len:0 live queue len:0
Nov 27 01:43:45 raspberrypi weewx[7964]: wmr200: MainThread: I Driver gracefully exiting
Nov 27 01:43:45 raspberrypi weewx[7964]: engine: Caught WeeWxIOError: USB polling thread unexpectedly terminated
Nov 27 01:43:45 raspberrypi weewx[7964]:     ****  Waiting 60 seconds then retrying...
Nov 27 01:44:45 raspberrypi weewx[7964]: engine: retrying...
Nov 27 01:44:45 raspberrypi weewx[7964]: engine: Using configuration file /usr/local/weewx/weewx.conf
Nov 27 01:44:45 raspberrypi weewx[7964]: engine: Debug is 1
Nov 27 01:44:45 raspberrypi weewx[7964]: engine: Initializing engine
Nov 27 01:44:45 raspberrypi weewx[7964]: engine: Loading station type WMR200 (weewx.drivers.wmr200)
Nov 27 01:44:45 raspberrypi weewx[7964]: wmr200: MainThread: I driver version is 3.3.5
Nov 27 01:44:45 raspberrypi weewx[7964]: wmr200: MainThread: I sensor map is {'outTempBatteryStatus': 'battery_status_out', 'outHumidity': 'humidity_1', 'rainRate': 'rain_rate', 'heatindex4': 'heatindex_5', 'rainTotal': 'rain_total', 'rainBatteryStatus':
Nov 27 01:44:45 raspberrypi weewx[7964]: wmr200: MainThread: I Created watchdog thread to poke for live data every 30 seconds
Nov 27 01:44:45 raspberrypi weewx[7964]: wmr200: MainThread: I Created USB polling thread to read block on device
Nov 27 01:44:45 raspberrypi weewx[7964]: wmr200: Thread-10: I USB polling device thread for live data launched
Nov 27 01:44:45 raspberrypi weewx[7964]: wmr200: MainThread: I Reset console device
Nov 27 01:44:45 raspberrypi weewx[7964]: wmr200: Thread-10: I USB polling device thread signaled to start
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: MainThread: W Restart count: 5
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: MainThread: D Configuration setup
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: MainThread: D   Log sensor faults: True
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: MainThread: D   Using PC Time: True
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: MainThread: D   Erase archive data: True
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: MainThread: D   Archive interval: 60
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: MainThread: D   Archive threshold: 604800
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Loading service weewx.engine.StdTimeSynch
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Finished loading service weewx.engine.StdTimeSynch
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Loading service weewx.engine.StdConvert
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: StdConvert target unit is 0x1
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Finished loading service weewx.engine.StdConvert
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Loading service weewx.engine.StdCalibrate
Nov 27 01:44:46 raspberrypi weewx[7964]: wmr200: Thread-9: I Started watchdog thread live data
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Finished loading service weewx.engine.StdCalibrate
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Loading service weewx.engine.StdQC
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Finished loading service weewx.engine.StdQC
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Loading service weewx.wxservices.StdWXCalculate
Nov 27 01:44:46 raspberrypi weewx[7964]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=hardware, windrun=prefer_hardware, heatindex=hardwar
Nov 27 01:44:46 raspberrypi weewx[7964]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Finished loading service weewx.wxservices.StdWXCalculate
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Loading service weewx.engine.StdArchive
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Archive will use data binding wx_binding
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Record generation will be attempted in 'hardware'
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: The archive interval in the configuration file (300) does not match the station hardware interval (60).
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Using archive interval of 60 seconds (specified by hardware)
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Use LOOP data in hi/low calculations: 1
Nov 27 01:44:46 raspberrypi weewx[7964]: manager: Daily summary version is 2.0
Nov 27 01:44:46 raspberrypi weewx[7964]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Nov 27 01:44:46 raspberrypi weewx[7964]: manager: Starting backfill of daily summaries
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.engine.StdArchive
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.restx.StdStationRegistry
Nov 27 01:44:47 raspberrypi weewx[7964]: restx: StationRegistry: Station will be registered.
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.restx.StdStationRegistry
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.restx.StdWunderground
Nov 27 01:44:47 raspberrypi weewx[7964]: restx: WU essentials: {'outTemp': 'True', 'barometer': 'True'}
Nov 27 01:44:47 raspberrypi weewx[7964]: restx: Wunderground-PWS: Data for station KNHNOTTI4 will be posted
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.restx.StdWunderground
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.restx.StdPWSweather
Nov 27 01:44:47 raspberrypi weewx[7964]: restx: PWSWeather: Data for station KNHNOTI4 will be posted
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.restx.StdPWSweather
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.restx.StdCWOP
Nov 27 01:44:47 raspberrypi weewx[7964]: restx: CWOP: Posting not enabled.
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.restx.StdCWOP
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.restx.StdWOW
Nov 27 01:44:47 raspberrypi weewx[7964]: restx: WOW: Posting not enabled.
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.restx.StdWOW
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.restx.StdAWEKAS
Nov 27 01:44:47 raspberrypi weewx[7964]: restx: AWEKAS: Posting not enabled.
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.restx.StdAWEKAS
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.engine.StdPrint
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.engine.StdPrint
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Loading service weewx.engine.StdReport
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Finished loading service weewx.engine.StdReport
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Starting up weewx version 3.9.0a3
Nov 27 01:44:47 raspberrypi weewx[7964]: engine: Station does not support reading the time
Nov 27 01:44:47 raspberrypi weewx[7964]: wmr200: MainThread: D genStartup() phase getting archive packets since 2018-11-27 01:43:00 EST (1543300980)
Nov 27 01:44:47 raspberrypi weewx[7964]: wmr200: MainThread: D   Acknowledged control packet rx:5769
Nov 27 01:44:47 raspberrypi weewx[7964]: manager: Daily summary version is 2.0
Nov 27 01:44:47 raspberrypi weewx[7964]: manager: Daily summary version is 2.0
Nov 27 01:44:48 raspberrypi weewx[7964]: wmr200: MainThread: D   Queuing archive packet rx:5 archive_queue_len:1
Nov 27 01:44:49 raspberrypi weewx[7964]: wmr200: MainThread: I genStartup() Delaying archive packet processing until live packet received
Nov 27 01:44:50 raspberrypi weewx[7964]: wmr200: MainThread: I genStartup() Delaying archive packet processing until live packet received
Nov 27 01:44:50 raspberrypi weewx[7964]: wmr200: MainThread: I genStartup() Delaying archive packet processing until live packet received
Nov 27 01:44:50 raspberrypi weewx[7964]: wmr200: MainThread: I Time drift between host and console in seconds:-3670
Nov 27 01:44:50 raspberrypi weewx[7964]: wmr200: MainThread: D   Queuing live packet rx:16193 live_queue_len:1
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I genStartup() Still receiving archive packets cnt:0 len:1
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I Using pc time adjusting archive record time by -3670 sec 2018-11-27 02:45:00 EST (1543304700) => 2018-11-27 01:43:50 EST (1543301030)
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: D   Initializing Archive Data.rain_total_last to 111.33
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: D genStartup() Yielding received archive record cnt:1 after requested timestamp:1543300980 pkt_interval:50 pkt:2018-11-27 01:43:50 EST (1543301030)
Nov 27 01:44:51 raspberrypi weewx[7964]: manager: Added record 2018-11-27 01:43:50 EST (1543301030) to database 'weewx.sdb'
Nov 27 01:44:51 raspberrypi weewx[7964]: engine: Main loop exiting. Shutting engine down.
Nov 27 01:44:51 raspberrypi weewx[7964]: restx: Shut down PWSWeather thread.
Nov 27 01:44:51 raspberrypi weewx[7964]: restx: Shut down Wunderground-PWS thread.
Nov 27 01:44:51 raspberrypi weewx[7964]: restx: Shut down StationRegistry thread.
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: Thread-10: I USB polling device thread exiting
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I USB polling thread expired
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: Thread-9: I Watchdog received shutdown
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: Thread-9: I Watchdog thread exiting
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I Watchdog thread expired
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I Received packet count live:16193 archive:5 control:5769
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I Received bytes:424 sent bytes:48
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I Packet archive queue len:0 live queue len:1
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: W Exiting with packets still in live queue cnt:1
Nov 27 01:44:51 raspberrypi weewx[7964]: wmr200: MainThread: I Driver gracefully exiting
Nov 27 01:44:51 raspberrypi weewx[7964]: engine: Caught unrecoverable exception in engine:
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****  'str' object is not callable
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****  Traceback (most recent call last):
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/engine.py", line 886, in main
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      engine.run()
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/engine.py", line 160, in run
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/engine.py", line 224, in dispatchEvent
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      callback(event)
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/engine.py", line 516, in startup
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      self._catchup(self.engine.console.genStartupRecords)
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/engine.py", line 631, in _catchup
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      origin='hardware'))
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/engine.py", line 224, in dispatchEvent
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      callback(event)
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/engine.py", line 597, in new_archive_record
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      dbmanager.addRecord(event.record, accumulator=self.old_accumulator)
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/manager.py", line 246, in addRecord
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      self._addSingleRecord(record, cursor, log_level)
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/manager.py", line 1212, in _addSingleRecord
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      _weight = self._calc_weight(record)
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****    File "/usr/local/weewx/bin/weewx/manager.py", line 1582, in _calc_weight
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****      raise ValueError("Non-positive value for record field 'interval': %s" (record['interval'], ))
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****  TypeError: 'str' object is not callable
Nov 27 01:44:51 raspberrypi weewx[7964]:     ****  Exiting.
lines 16732-16774/16774 (END)

**Comment by tkeffer** [comment] 2018-11-29 00:01
There are two different things going on here.

First, there is a formatting error when creating the error message. This is what caused the `TypeError` exception. This has been fixed in commit https://github.com/weewx/weewx/commit/d47142b779a2ad68e0f01fca6f9f84cbe4221cda

The second problem is that, somehow, the `interval` field was either zero, or negative. We don't know which because of problem number one.

I suspect the problem is related to the very big "clock drift" reported on 01:44:50.

Does this error occur on every startup? Or, just once?

**Comment by lylavoie** [comment] 2018-11-29 01:33
So far, I've only seen this once, it ran for a day or so, then I noticed data wasn't being reported to Wunderground, so checked it and saw the error.   I'll pull the updated version and see if the issue arises again.  

I'm surprised about the drift, the Rasp Pi has ntp configured and operational and the station should be pulling time from the NIST WWVB radio clock.  I'll dig into that issue a little bit.  I also see a difference in the hardware archive interval and the 300 seconds configured in weewx.

**Comment by tkeffer** [comment] 2018-12-05 23:42
Anything new on this?

**Comment by tkeffer** [comment] 2018-12-06 12:15
The only patch I've done is one that fixes the error message. It didn't fix the underlying problem.

Still, I'll close the issue. We can open it again if it reoccurs.

**Closed by tkeffer** 2018-12-06 12:15 UTC
