### ISSUE TITLE
`wee_database` `-fix-strings`/`--fix-strings` fails on unpatched databases containing 'null strings'

### ISSUE THREAD

**Issue by gjr80** [weewx/weewx#695] opened 2021-08-27 07:45 UTC
`wee_database` `--check-strings`/`--fix-strings` fails on v1.0-v3.0 databases containing 'null strings' as the database cannot be patched to v4.0 due to the embedded 'null strings'. The 'null strings' cannot be removed/repaired due to the unpatched state of the database and the database cannot be patched due to the 'null strings' embedded in the database.

Refer to [this weewx-user thread](https://groups.google.com/g/weewx-user/c/HXGIfGCI4wc/m/hVuBQhLpAgAJ).

**Comment by gjr80** [comment] 2021-08-29 06:02
PR #696 should address this corner case, need to wait and see how the user with the problem fares. Not 100% happy how it turned out so happy to take on any advice, hence the RP rather than a direct commit.

**Comment by tkeffer** [comment] 2021-09-24 14:38
I guess another solution would be to catch the exception that occurs when trying to convert from string to float and, if it occurs, set the value to `None`.

This is all that `--fix-strings` does anyway. It would obviate the need for `--check-strings` and `--fix-strings`.

**Comment by gjr80** [comment] 2021-09-26 12:17
Been a while since I worked on this and my brain is not too sharp tonite. When you say '_catch the exception that occurs when trying to convert from string to float_', do you mean catching the exception when the malformed field is added to the accumulators? Will that fix a string in the archive? Can see it will keep the daily summaries string free but that was not the issue. Or do I have this all wrong - refer to my first sentence.

**Comment by tkeffer** [comment] 2021-09-26 12:27
If you go back to the original [weewx-user thread](https://groups.google.com/g/weewx-user/c/HXGIfGCI4wc/m/hVuBQhLpAgAJ) that started this, you'll see that the problem is that the user had a string in his database, which caused a `ValueError` exception. Normally, we tell the user to fix their database using `--fix-strings`. What `--fix-strings` does is search for all strings, and set them to `None`.

I'm suggesting that we suppress the original exception and, instead, set the value to `None`. Change this

```python
        #  If this is a string, try to convert it to a float.
        if isinstance(val, (six.string_types, six.text_type)):
            # Fail hard if unable to do the conversion:
            val = to_float(val)
```

to this

```python
        #  If this is a string, try to convert it to a float.
        try:
            val = to_float(val)
        except ValueError:
            val = None
```

This will also cause the "upgrade" of the daily summaries to finish cleanly.

**Comment by gjr80** [comment] 2021-09-26 12:46
Can see this would cause the "upgrade" of the daily summaries to finish cleanly but I don't see it doing anything to the archive, so the archive will still have a string somewhere? That would still need to be fixed with `--fix-strings`.

**Comment by tkeffer** [comment] 2021-09-26 13:33
Yup. It would still have strings, but they wouldn't matter.

But, if the user so chooses, s/he can still run `--fix-strings`.

**Comment by gjr80** [comment] 2021-09-26 13:52
In that case your approach is much neater and less complex. Do you want to apply the changes to `accum.py`, I would but I didn't go to bed till 230am this morning and consequently have been crap all day. Reckon I would mess up those half dozen lines if I did them now. I'll kill PR #695 now, that I can do.

**Comment by tkeffer** [comment] 2021-09-26 14:29
I'll take care of it.

**Comment by tkeffer** [comment] 2021-09-26 15:44
Fixed with commit https://github.com/weewx/weewx/commit/6c8e910f045a4d0484d9d039909d7827dc1b42b5

**Closed by tkeffer** 2021-09-26 15:44 UTC
Labels: bug
