### ISSUE TITLE
weewx www-site down

### ISSUE THREAD

**Issue by Calathia** [weewx/weewx#317] opened 2018-04-19 06:02 UTC
www.weewx.com has been down for a while. Any idea why?

**Comment by matthewwall** [comment] 2018-04-19 09:49
confirmed that weewx.com is not responding to ssh or http requests as of at least 05:30 on 19apr2018 (us eastern time)

**Comment by tkeffer** [comment] 2018-04-19 13:05
Works for me.

Frankly, this happened on Sunday as well. I ended up rebooting the VM. However, now I wonder if it was just being unresponsive, but still running.

**Comment by tkeffer** [comment] 2018-04-28 15:09
We think we've identified the problem as a runaway process that was using all the CPU cycles. 

Closing issue.

**Closed by tkeffer** 2018-04-28 15:09 UTC

**Comment by MichaelAronsen** [comment] 2019-07-26 11:58
this seems to be happning again?

**Comment by tkeffer** [comment] 2019-07-27 01:19
Tough crowd! 

The site was down for about 20 minutes this morning because of an unintended webserver "upgrade."

**Comment by MichaelAronsen** [comment] 2019-07-27 08:59
Well you told me to upgrade my weewx and since there are no mirrors, that was hard
