### ISSUE TITLE
Add ftp_upload_interval parameter to reduce/limit fees for cellular network data access subscription

### ISSUE THREAD

**Issue by yannick56** [weewx/weewx#108] opened 2016-02-26 13:03 UTC
Hello, 

Documentation at http://www.weewx.com/docs/usersguide.htm#archive_interval129 said that "archive_interval" parameter is used to define interval between weewx reports generation and
FTP upload interval has the same value than "archive_interval" because http://www.weewx.com/docs/usersguide.htm#[[StandardReport]] with its FTP subpart said 
"This is the standard report that will be run on every archiving interval."

I want to use a cellular network access to upload weewx data on a free website for all the internet users but the fees for cellular network data access subscription are expensive and I have a low data quota with it. 
Can you add a ftp_upload_interval parameter in weewx ?
It will be very useful for me because I could generated reports each 5mn on my private network and then upload weewx data reports each hour to make them available for alls the internet users in the world. 

Thank you

**Comment by tkeffer** [comment] 2016-02-26 13:06
Duplicate of issue #17.

**Closed by tkeffer** 2016-02-26 13:06 UTC
